name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.0.9
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  google_nav_bar: ^5.0.6
  google_maps_flutter: ^2.5.3
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
